name: Tools - Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: none
      pull-requests: write
      repository-projects: none
      security-events: none
    steps:
      - name: Run release drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}